"""empty message

Revision ID: 570f2d0dbd3b
Revises: 03b2e6d6dff3
Create Date: 2021-06-25 10:05:28.983398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '570f2d0dbd3b'
down_revision = '03b2e6d6dff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_webhook',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('json_body', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('xml_body', sa.TEXT(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('login', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_webhook')
    # ### end Alembic commands ###
