"""empty message

Revision ID: b93904cef357
Revises: abcf1e6d0fd6
Create Date: 2021-04-28 17:45:58.883727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b93904cef357'
down_revision = 'abcf1e6d0fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('second_table_with_timezone3',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('json_body', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('xml_body', sa.TEXT(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('login', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('second_table_with_timezone2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('second_table_with_timezone2',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('json_body', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('xml_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='second_table_with_timezone2_pkey')
    )
    op.drop_table('second_table_with_timezone3')
    # ### end Alembic commands ###
